### ISSUE TITLE
Publishing to Terraform registry

### ISSUE THREAD

**Issue by jwillebrands** [kyma-incubator/terraform-provider-kind#23]
Heya! Is there any chance for this provider to be published to the Terraform registry? I see that @unicell has a fork that has been published, but it is currently two versions behind. Are there any plans to merge that effort into this repository? It would be great to have an easy way to pull in this provider.

**Comment by tehcyx** [comment]
Hi @jwillebrands, 

Yes, we'd pretty much like to have this provider in the registry. Some of the last efforts made were in preparation for this, e.g. adding documentation in the format required for the registry. I'd like to merge a bigger feature first, that I'm currently working on, before doing taking that step though.

**Comment by unicell** [comment]
Thanks for bringing it up @jwillebrands !

@tehcyx Glad to hear we're pushing forward to make this provider available in Terraform registry. I've already sent one documentation PR back a while ago. Thanks for merging it! There's one more `goreleaser` change[1] which is required for publishing to Terraform registry.

I didn't send the patch back last time, because I realized `kyma-incubator/terraform-provider-kind` already has it's own published releases (with some process not yet undocumented). And because `goreleaser` change requires corresponding GPG private key to be set in Github settings for the project.

With that said, let me know if you wanna me to send the goreleaser change back if that is helpful.

[1] https://github.com/unicell/terraform-provider-kind/commit/d958d48a26b5a006f3b35e22ee5ac10579aa5389

**Comment by tehcyx** [comment]
Hey @unicell,

Is there documentation around what I need to do for the GPG key? I'd assume we have to use some kind of bot account to do this?

Currently the release process is super manual. I build the binaries locally and attach them in the GitHub release.

**Comment by unicell** [comment]
@tehcyx Yes, you're right. Github action is the way to do in order to streamline the process. And this is the doc from Terraform

https://www.terraform.io/docs/registry/providers/publishing.html#github-actions-preferred-

For goreleaser to work together with Github Action, GPG private key is set in Project's secret setting page, and passed to Github action through a variable.

**Comment by tehcyx** [comment]
@unicell I'd be happy to merge a PR with the goreleaser changes, so that after I merge the feature I'm creating currently we can maybe already use the GH Action to do the next release and get started with the registry right after.

**Comment by unicell** [comment]
@tehcyx Thanks! PR filed https://github.com/kyma-incubator/terraform-provider-kind/pull/25

**Comment by tehcyx** [comment]
I've opened https://github.com/kyma-incubator/terraform-provider-kind/pull/26 as draft for anyone eager enough to try, but still need to fix at least one test and change documentation.
Also over time we'll need more test scenarios eventually.

**Comment by jwillebrands** [comment]
That is awesome, thanks a lot for the effort everyone. Much appreciated! I will give that version a spin.

**Comment by tehcyx** [comment]
Necessary PRs are merged, release pending and waiting for HashiCorp to accept my public key for publication.

**Comment by tehcyx** [comment]
The provider is now published: https://registry.terraform.io/providers/kyma-incubator/kind/latest
